services:
  postgres_test:
    image: postgres:15-alpine # Use uma versão recente
    container_name: typegorm_postgres_test
    networks:
      - nemesis-starter_nemesis 
    environment:
      POSTGRES_USER: admin # Default user
      POSTGRES_PASSWORD: password # Senha definida aqui
      POSTGRES_DB: testdb # Banco de dados de teste
    ports:
      - "5432:5432" # Expõe a porta padrão do host
    volumes:
      - pg_test_data:/var/lib/postgresql/data # Volume opcional para persistir dados
  mysql_test:
    image: mysql:8.0 # Ou use mariadb:latest
    container_name: typegorm_mysql_test
    networks:
      - nemesis-starter_nemesis 
    environment:
      MYSQL_ROOT_PASSWORD: password # Senha para o usuário root
      MYSQL_DATABASE: testdb # Cria banco de dados de teste
    ports:
      - "3307:3306" # Expõe porta padrão do MySQL
    volumes:
      - mysql_test_data:/var/lib/mysql
  mongo_test:
    image: mongo:latest # Usar uma versão recente
    container_name: typegorm_mongo_test
    networks:
      - nemesis-starter_nemesis
    ports:
      - "27017:27017" # Porta padrão MongoDB
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=testdb
    volumes:
      - mongo_test_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  sqlserver_test:
    image: mcr.microsoft.com/mssql/server:2022-latest # Imagem oficial Linux
    container_name: typegorm_sqlserver_test
    networks:
      - nemesis-starter_nemesis
    environment:
      ACCEPT_EULA: "Y" # Obrigatório para aceitar a licença
      MSSQL_SA_PASSWORD: "yourStrong(!)Password" # Defina uma senha forte aqui!
      # MSSQL_PID: "Developer" # Opcional: Edição (Developer é gratuita)
    ports:
      - "1433:1433" # Porta padrão SQL Server
    volumes:
      - sqlserver_test_data:/var/opt/mssql
volumes:
  pg_test_data:
  mysql_test_data:
  mongo_test_data:
  sqlserver_test_data:

networks:
  nemesis-starter_nemesis:
    name: nemesis-starter_nemesis
    external: true
      
